name: Docker-Version
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make docker-build
    - name: Test run the Docker image
      run: apt-get install procps &&\
        docker run --rm -p 8888:8888 -e DOCKER_STACKS_JUPYTER_CMD=notebook mtlulka/aoc2022 &\
        kill -9 $(lsof -n -i4TCP:8888 | cut -f 2 -d " ")
