name: Notebook-Version
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Update pip and install Jupyter Notebook
      run: |
        pip install --upgrade pip &&\
          pip install notebook
    - name: Install dependencies
      run: |
        make jup-install
    - name: Clean dependencies
      run: |
        make jup-clean
